dist: trusty
sudo: required
language: node_js
node_js:
- '7'
services:
  - docker
script:
  - npm run webpack
branches:
  only:
  - master
deploy:
  - provider: script
    script: "./deploy.sh XO"
    skip_cleanup: true
    on:
      branch: master
