language: node_js

sudo: required

node_js:
  - 7

services:
  - docker

install: true

script:
  - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
  
  - docker images --all
  - docker build -t registry.heroku.com/xogame123/web .
  - docker push registry.heroku.com/xogame123/web
