dist: trusty
sudo: required
language: node_js
node_js:
- '7'
services:
  - docker
 
script:
  - npm run webpack
  - docker login --username=_ --password=$(echo $API_KEY) registry.heroku.com
  - docker build -t registry.heroku.com/XOgame/web .
  - docker push registry.heroku.com/XOgame/web
